### ISSUE TITLE
Error message pandoc colors

### ISSUE THREAD

**Issue by andreasmhallberg** [davidosomething/vim-colors-meh#7]
When I open a markdown file I get the following error message:

```
Error detected while processing Syntax Autocommands for "*pandoc*":
E492: Not an editor command:     meh#PandocColors()|  endif
```

**Comment by davidosomething** [comment]
This is because either

1. you did not install the entire plugin properly, the function is provided by the autoload/meh.vim file, which needs to be added to runtime path. Using a plugin manager such as vim-plug or adding the directories will fix it

or 

2. you can add `let g:meh_pandoc_enabled=0` to disable special pandoc handling when using markdown
